name: Tests (s390x)

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
    paths-ignore:
    - '**.rst'

jobs:
  linux-s390x:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Build & test
      uses: uraimo/run-on-arch-action@v3
      with:
        arch: s390x
        distro: ubuntu22.04
        install: |
          apt-get update -q -y
          apt-get install -q -y cmake libssl-dev python3-dev python3-venv wget
        run: |
          LIBSSH2_VERSION=1.11.1 LIBGIT2_VERSION=1.9.1 /bin/sh build.sh test
      continue-on-error: true # Tests are expected to fail, see issue #812
